;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Act1.Level1",DevComment="Tags for Act 1 level flow")
+GameplayTagList=(Tag="Act1.Level2",DevComment="Tags for Act 1 level flow")
+GameplayTagList=(Tag="Act1.Level3",DevComment="Tags for Act 1 level flow")
+GameplayTagList=(Tag="Act1.Level4",DevComment="Tags for Act 1 level flow")
+GameplayTagList=(Tag="Act1.Level5",DevComment="Tags for Act 1 level flow")
+GameplayTagList=(Tag="Game.Act1.Active",DevComment="Tags for Act 1 level flow")

